Repository PatrickYoussef/SOEN341Project, pull requests merged in 2020-04, with the labels that each got.

#55 Users are created
  StockHut/StockHut/ClientApp/.env-cmdrc
  StockHut/StockHut/ClientApp/src/App.js
  StockHut/StockHut/ClientApp/src/components/Home.js
  StockHut/StockHut/ClientApp/src/components/NewsFeed.js
  StockHut/StockHut/ClientApp/src/components/Signup.js
  StockHut/StockHut/Controllers/UsersController.cs
  StockHut/StockHut/Controllers/WeatherForecastController.cs
  StockHut/StockHut/Interfaces/ITokenCreator.cs
  StockHut/StockHut/Models/StockHutContext.cs
  StockHut/StockHut/Models/TokenCreator.cs
  StockHut/StockHut/Models/Users.cs
  StockHut/StockHut/Models/WeatherForecast.cs
  StockHut/StockHut/Program.cs
  StockHut/StockHut/Startup.cs
  StockHut/StockHut/StockHut.csproj
Labels: bug, enhancement, task

#58 Soen341 407
  StockHut/StockHut/ClientApp/src/components/Home.js
  StockHut/StockHut/ClientApp/src/components/NewsFeed.js
  StockHut/StockHut/ClientApp/src/components/Signup.js
Labels: bug

#59 google doc link for final report
  documentation/google doc link for final report
Labels: documentation

#62 Soen341_408 User Profile UI
  StockHut/StockHut/ClientApp/src/App.js
  StockHut/StockHut/ClientApp/src/components/Navbar/NavDrawer.js
  StockHut/StockHut/ClientApp/src/components/Profile.js
Labels: Extra features

#64 Contactus Page
  StockHut/StockHut/ClientApp/package-lock.json
  StockHut/StockHut/ClientApp/package.json
  StockHut/StockHut/ClientApp/src/App.js
  StockHut/StockHut/ClientApp/src/components/ContactUs.js
  StockHut/StockHut/ClientApp/src/components/Navbar/NavDrawer.js
Labels: Extra features, P3

#66 Following
  StockHut/StockHut/ClientApp/src/components/FriendPage/Friends.js
  StockHut/StockHut/ClientApp/src/components/Navbar/NavDrawer.js
  StockHut/StockHut/ClientApp/src/components/Navbar/Navbar.js
  StockHut/StockHut/ClientApp/src/components/NewsFeed.js
  StockHut/StockHut/Controllers/UsersController.cs
  StockHut/StockHut/Interfaces/ITokenCreator.cs
  StockHut/StockHut/Models/TokenCreator.cs
Labels: P2, bug, good first issue, task

#67 Documentation update, acceptance test for sprint 4
  documentation/Acceptance testing for every user story.md
  documentation/precedence network.png
  documentation/risk.png
Labels: test cases

#70 following works
  .gitignore
  SCREENSHOTS.pdf
  StockHut/StockHut/ClientApp/report.20200408.003415.45700.0.001.json
  StockHut/StockHut/ClientApp/src/App.js
  StockHut/StockHut/ClientApp/src/components/FriendPage/Friends.js
  StockHut/StockHut/ClientApp/src/components/Navbar/NavDrawer.js
  StockHut/StockHut/ClientApp/src/components/Navbar/NavMenu.js
  StockHut/StockHut/ClientApp/src/components/Navbar/Navbar.js
  StockHut/StockHut/ClientApp/src/components/NewsFeed.js
  StockHut/StockHut/ClientApp/src/components/Profile.js
  StockHut/StockHut/Controllers/UsersController.cs
  StockHut/StockHut/Interfaces/ITokenCreator.cs
  StockHut/StockHut/Models/TokenCreator.cs
Labels: bug

#80 Changes to profile page
  StockHut/StockHut/ClientApp/package-lock.json
  StockHut/StockHut/ClientApp/package.json
  StockHut/StockHut/ClientApp/src/components/Profile.js
Labels: Extra features, P1, enhancement
