Repository PatrickYoussef/SOEN341Project, pull requests merged in 2020-03, with the labels that each got.

#35 precedence network
  documentation/Acceptance test for project in spread sheet
  documentation/mvc.png
  documentation/precedence network.png
  documentation/risk.png
  precedence network.png
Labels: documentation

#36 Added a feed
  .gitignore
  StockHut/StockHut/ClientApp/package-lock.json
  StockHut/StockHut/ClientApp/package.json
  StockHut/StockHut/ClientApp/src/App.js
  StockHut/StockHut/ClientApp/src/components/Home.js
  StockHut/StockHut/ClientApp/src/components/NavBar.js
  StockHut/StockHut/ClientApp/src/components/NavDrawer.js
  StockHut/StockHut/ClientApp/src/components/NewsFeed.js
  StockHut/StockHut/ClientApp/src/components/Signup.js
  StockHut/StockHut/ClientApp/src/login/login.css
  StockHut/StockHut/ClientApp/src/login/signup.js
Labels: enhancement, task

#37 Soen341 301
  StockHut/StockHut/ClientApp/src/App.js
  StockHut/StockHut/ClientApp/src/components/Home.js
  StockHut/StockHut/ClientApp/src/components/Layout.js
  StockHut/StockHut/ClientApp/src/components/LogIn.js
  StockHut/StockHut/ClientApp/src/components/NavBar.js
  StockHut/StockHut/ClientApp/src/components/NavDrawer.js
  StockHut/StockHut/ClientApp/src/components/NavMenu.css
  StockHut/StockHut/ClientApp/src/components/NavMenu.js
  StockHut/StockHut/ClientApp/src/components/Navbar/NavDrawer.js
  StockHut/StockHut/ClientApp/src/components/Navbar/NavMenu.css
  StockHut/StockHut/ClientApp/src/components/Navbar/NavMenu.js
  StockHut/StockHut/ClientApp/src/components/Navbar/Navbar.js
  StockHut/StockHut/ClientApp/src/components/Profile.js
  StockHut/StockHut/ClientApp/src/components/Signup.js
  StockHut/StockHut/Controllers/UsersController.cs
  StockHut/StockHut/DbContext-StockHut.cs
  StockHut/StockHut/Models/StockHutContext.cs
  StockHut/StockHut/Models/Users.cs
  StockHut/StockHut/StockHut.csproj
Labels: enhancement

#50 Signup and Login
  StockHut/StockHut/ClientApp/package-lock.json
  StockHut/StockHut/ClientApp/package.json
  StockHut/StockHut/ClientApp/src/App.js
  StockHut/StockHut/ClientApp/src/components/Home.js
  StockHut/StockHut/ClientApp/src/components/LogIn.js
  StockHut/StockHut/ClientApp/src/components/NewsFeed.js
  StockHut/StockHut/ClientApp/src/components/Profile.js
  StockHut/StockHut/ClientApp/src/components/Signup.js
  StockHut/StockHut/appsettings.json
  StockHut/StockHut/data.env
Labels: enhancement
